// Code generated by "stringer -type=AccountType"; DO NOT EDIT

package buchfuehrung

import "fmt"

const _AccountType_name = "UnkownGiroKonto"

var _AccountType_index = [...]uint8{0, 6, 15}

func (i AccountType) String() string {
	if i >= AccountType(len(_AccountType_index)-1) {
		return fmt.Sprintf("AccountType(%d)", i)
	}
	return _AccountType_name[_AccountType_index[i]:_AccountType_index[i+1]]
}
